version: '3.7'

services:
  nginx:
    build: .
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - node
  node:
    image: artemeesenin/simple-node-message
    ports:
      - "3000:3000"

